# File: .github/workflows/main.yml

name: Create Issue

on:
  workflow_dispatch:
    inputs:
      title: { description: 'Issue title', required: true }
      body: { description: 'Issue body', required: true }

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { github, inputs } = require('@actions/github');
            const { owner, repo } = github.context.repo;
            
            github.issues.create({
              owner: 'sudorunoscar',
              repo: 'githubactions',
              title: inputs.title,
              body: inputs.body,
              labels: ['created-by-workflow']
            })
