name: Issue

on:
  workflow_dispatch:
    inputs:
      title: 
        description: 'Issue title'
        required: true
      body: 
        description: 'Issue body'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: github.event.inputs.title,
              body: github.event.inputs.body,
              labels: ['created-by-workflow']
            })
