# File: .github/workflows/main.yml

name: Create Issue

on:
  workflow_dispatch:
    inputs:
      title: { description: 'Issue title', required: true }
      body: { description: 'Issue body', required: true }

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const octokit = require('@octokit/rest')({
              auth: process.env.GITHUB_TOKEN
            });
            
            octokit.issues.create({
              owner: 'sudorunoscar',
              repo: 'githubactions',
              title: process.env.TITLE,
              body: process.env.BODY,
              labels: ['created-by-workflow']
            })
        env:
          TITLE: ${{ github.event.inputs.title }}
          BODY: ${{ github.event.inputs.body }}
